
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Site Config settings
title: Checkpoint
theme-color: #75BB6E
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This space is set aside for a basic couple o'sentence description of the site. What is it? What type of content should users expect to see here when they visit? Why should anyone care?
featured-tags:
  - Tag One
  - Tag Two
  - Tag Three
  - Tag Four
permalink: "/:title.html"
excerpt_separator: "<!--more-->"
collections:
  authors:
    title: Authors
    output: true
    permalink: "/authors/:path/"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    Author: 
    layout: post
    social-image:
    thumbnail: "800 x 400"
- scope:
    path: ''
    type: authors
  values:
    layout: author
    Job: 
    Image: 
# Build settings
markdown: kramdown
destination: "./build"
theme: dai-blogs
gems:
exclude:
  - ".gitignore"
  - gulpfile.js
  - package.json
  - browser-sync.js
  - ".jekyll-metadata"
  - Gemfile
  - Gemfile.lock
  - node_modules