---
title: A Unique Title
timezone: UTC
collections:
  authors:
    title: Authors
    output: true
    permalink: "/authors/:path/"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    Author: 
    layout: post
    social-image: 
    thumbnail: 800 x 400
- scope:
    path: ''
    type: authors
  values:
    layout: author
    Job: 
    Image: 
baseurl: ''
url: ''
theme-color: 
email: your-email@domain.com
description: 'This space is set aside for a basic couple o''sentence description of
  the site. What is it? What type of content should users expect to see here when
  they visit? Why should anyone care?

'
featured-tags:
- Tag One
- Tag Two
- Tag Three
- Tag Four
permalink: "/:title.html"
excerpt_separator: "<!--more-->"
markdown: kramdown
destination: "./build"
theme: dai-blogs
gems: 
exclude:
- ".gitignore"
- gulpfile.js
- package.json
- browser-sync.js
- ".jekyll-metadata"
- Gemfile
- Gemfile.lock
- node_modules
