---
title: Checkpoint
timezone: UTC
collections:
  authors:
    title: Authors
    output: true
    permalink: "/authors/:path/"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    Author: 
    layout: post
    social-image: 
    thumbnail: 800 x 400
- scope:
    path: ''
    type: authors
  values:
    layout: author
    Job: 
    Image: 235 x 235
theme-color: 
email: your-email@domain.com
description: "Where development and national security intersect. Research, applied
  learning, and fierce debates about measuring success and failure, about embracing
  new ideas and technologies, and about adapting concepts and practices from both
  the development and national defense disciplines are the foundation on which we
  have built DAI’s Center for Secure and Stable States."
featured-tags:
- Fragile States
- Research
- CVE
permalink: "/:title.html"
excerpt_separator: "<!--more-->"
baseurl: 
url: 
markdown: kramdown
destination: "./build"
gems: 
exclude:
- ".gitignore"
- gulpfile.js
- package.json
- browser-sync.js
- ".jekyll-metadata"
- Gemfile
- Gemfile.lock
- node_modules
