---
title: Checkpoint
timezone: UTC
collections:
  authors:
    title: Authors
    output: true
    permalink: "/authors/:path/"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    Author: 
    layout: post
    social-image: 
    thumbnail: 800 x 400
- scope:
    path: ''
    type: authors
  values:
    layout: author
    Job: 
    Image: 235 x 235
theme-color: 
email: your-email@domain.com
description: "**Where development and national security intersect.** Lorem ipsum dolor
  sit amet, eros etiam nec vivamus. Nec porta nulla nisl nunc, non nam justo tincidunt,
  ut litora praesent et urna donec, varius auctor condimentum nunc lacus urna deserunt,
  adipiscing eu dui. Suspendisse.\n"
featured-tags:
- Stabilization
- Fragile States
permalink: "/:title.html"
excerpt_separator: "<!--more-->"
baseurl: 
url: 
markdown: kramdown
destination: "./build"
gems: 
exclude:
- ".gitignore"
- gulpfile.js
- package.json
- browser-sync.js
- ".jekyll-metadata"
- Gemfile
- Gemfile.lock
- node_modules
